//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LajtIt.Bll.DpdStatusWCF {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/")]
    public partial class authDataV1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string channelField;
        
        private string loginField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string channel {
            get {
                return this.channelField;
            }
            set {
                this.channelField = value;
                this.RaisePropertyChanged("channel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
                this.RaisePropertyChanged("login");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/", ConfigurationName="DpdStatusWCF.DPDInfoServicesObjEvents")]
    public interface DPDInfoServicesObjEvents {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(LajtIt.Bll.DpdStatusWCF.Exception), Action="", Name="Exception")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LajtIt.Bll.DpdStatusWCF.markEventsAsProcessedV1Response markEventsAsProcessedV1(LajtIt.Bll.DpdStatusWCF.markEventsAsProcessedV1Request request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(LajtIt.Bll.DpdStatusWCF.Exception), Action="", Name="Exception")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LajtIt.Bll.DpdStatusWCF.getEventsForCustomerV1Response getEventsForCustomerV1(LajtIt.Bll.DpdStatusWCF.getEventsForCustomerV1Request request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(LajtIt.Bll.DpdStatusWCF.Exception), Action="", Name="Exception")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LajtIt.Bll.DpdStatusWCF.getEventsForCustomerV2Response getEventsForCustomerV2(LajtIt.Bll.DpdStatusWCF.getEventsForCustomerV2Request request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(LajtIt.Bll.DpdStatusWCF.Exception), Action="", Name="Exception")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LajtIt.Bll.DpdStatusWCF.getEventsForWaybillV1Response getEventsForWaybillV1(LajtIt.Bll.DpdStatusWCF.getEventsForWaybillV1Request request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(LajtIt.Bll.DpdStatusWCF.Exception), Action="", Name="Exception")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LajtIt.Bll.DpdStatusWCF.getEventsForCustomerV3Response getEventsForCustomerV3(LajtIt.Bll.DpdStatusWCF.getEventsForCustomerV3Request request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(LajtIt.Bll.DpdStatusWCF.Exception), Action="", Name="Exception")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LajtIt.Bll.DpdStatusWCF.getEventsForCustomerV4Response getEventsForCustomerV4(LajtIt.Bll.DpdStatusWCF.getEventsForCustomerV4Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="markEventsAsProcessedV1", WrapperNamespace="http://events.dpdinfoservices.dpd.com.pl/", IsWrapped=true)]
    public partial class markEventsAsProcessedV1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string confirmId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LajtIt.Bll.DpdStatusWCF.authDataV1 authDataV1;
        
        public markEventsAsProcessedV1Request() {
        }
        
        public markEventsAsProcessedV1Request(string confirmId, LajtIt.Bll.DpdStatusWCF.authDataV1 authDataV1) {
            this.confirmId = confirmId;
            this.authDataV1 = authDataV1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="markEventsAsProcessedV1Response", WrapperNamespace="http://events.dpdinfoservices.dpd.com.pl/", IsWrapped=true)]
    public partial class markEventsAsProcessedV1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public markEventsAsProcessedV1Response() {
        }
        
        public markEventsAsProcessedV1Response(bool @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/")]
    public partial class customerEventsResponseV1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string confirmIdField;
        
        private customerEventV1[] eventsListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string confirmId {
            get {
                return this.confirmIdField;
            }
            set {
                this.confirmIdField = value;
                this.RaisePropertyChanged("confirmId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("eventsList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public customerEventV1[] eventsList {
            get {
                return this.eventsListField;
            }
            set {
                this.eventsListField = value;
                this.RaisePropertyChanged("eventsList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/")]
    public partial class customerEventV1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string businessCodeField;
        
        private string countryField;
        
        private string depotField;
        
        private string descriptionField;
        
        private string eventData1Field;
        
        private string eventData2Field;
        
        private string eventData3Field;
        
        private string eventTimeField;
        
        private long idField;
        
        private long objectIdField;
        
        private string operationTypeField;
        
        private string packageReferenceField;
        
        private string parcelReferenceField;
        
        private string waybillField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string businessCode {
            get {
                return this.businessCodeField;
            }
            set {
                this.businessCodeField = value;
                this.RaisePropertyChanged("businessCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string depot {
            get {
                return this.depotField;
            }
            set {
                this.depotField = value;
                this.RaisePropertyChanged("depot");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string eventData1 {
            get {
                return this.eventData1Field;
            }
            set {
                this.eventData1Field = value;
                this.RaisePropertyChanged("eventData1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string eventData2 {
            get {
                return this.eventData2Field;
            }
            set {
                this.eventData2Field = value;
                this.RaisePropertyChanged("eventData2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string eventData3 {
            get {
                return this.eventData3Field;
            }
            set {
                this.eventData3Field = value;
                this.RaisePropertyChanged("eventData3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string eventTime {
            get {
                return this.eventTimeField;
            }
            set {
                this.eventTimeField = value;
                this.RaisePropertyChanged("eventTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public long objectId {
            get {
                return this.objectIdField;
            }
            set {
                this.objectIdField = value;
                this.RaisePropertyChanged("objectId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string operationType {
            get {
                return this.operationTypeField;
            }
            set {
                this.operationTypeField = value;
                this.RaisePropertyChanged("operationType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string packageReference {
            get {
                return this.packageReferenceField;
            }
            set {
                this.packageReferenceField = value;
                this.RaisePropertyChanged("packageReference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string parcelReference {
            get {
                return this.parcelReferenceField;
            }
            set {
                this.parcelReferenceField = value;
                this.RaisePropertyChanged("parcelReference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string waybill {
            get {
                return this.waybillField;
            }
            set {
                this.waybillField = value;
                this.RaisePropertyChanged("waybill");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEventsForCustomerV1", WrapperNamespace="http://events.dpdinfoservices.dpd.com.pl/", IsWrapped=true)]
    public partial class getEventsForCustomerV1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int limit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LajtIt.Bll.DpdStatusWCF.authDataV1 authDataV1;
        
        public getEventsForCustomerV1Request() {
        }
        
        public getEventsForCustomerV1Request(int limit, LajtIt.Bll.DpdStatusWCF.authDataV1 authDataV1) {
            this.limit = limit;
            this.authDataV1 = authDataV1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEventsForCustomerV1Response", WrapperNamespace="http://events.dpdinfoservices.dpd.com.pl/", IsWrapped=true)]
    public partial class getEventsForCustomerV1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LajtIt.Bll.DpdStatusWCF.customerEventsResponseV1 @return;
        
        public getEventsForCustomerV1Response() {
        }
        
        public getEventsForCustomerV1Response(LajtIt.Bll.DpdStatusWCF.customerEventsResponseV1 @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEventsForCustomerV2", WrapperNamespace="http://events.dpdinfoservices.dpd.com.pl/", IsWrapped=true)]
    public partial class getEventsForCustomerV2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int limit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string language;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LajtIt.Bll.DpdStatusWCF.authDataV1 authDataV1;
        
        public getEventsForCustomerV2Request() {
        }
        
        public getEventsForCustomerV2Request(int limit, string language, LajtIt.Bll.DpdStatusWCF.authDataV1 authDataV1) {
            this.limit = limit;
            this.language = language;
            this.authDataV1 = authDataV1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEventsForCustomerV2Response", WrapperNamespace="http://events.dpdinfoservices.dpd.com.pl/", IsWrapped=true)]
    public partial class getEventsForCustomerV2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LajtIt.Bll.DpdStatusWCF.customerEventsResponseV1 @return;
        
        public getEventsForCustomerV2Response() {
        }
        
        public getEventsForCustomerV2Response(LajtIt.Bll.DpdStatusWCF.customerEventsResponseV1 @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/")]
    public enum eventsSelectTypeEnum {
        
        /// <remarks/>
        ALL,
        
        /// <remarks/>
        ONLY_LAST,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/")]
    public partial class customerEventsResponseV3 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string confirmIdField;
        
        private customerEventV3[] eventsListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string confirmId {
            get {
                return this.confirmIdField;
            }
            set {
                this.confirmIdField = value;
                this.RaisePropertyChanged("confirmId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("eventsList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public customerEventV3[] eventsList {
            get {
                return this.eventsListField;
            }
            set {
                this.eventsListField = value;
                this.RaisePropertyChanged("eventsList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/")]
    public partial class customerEventV3 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string businessCodeField;
        
        private string countryField;
        
        private string depotField;
        
        private string depotNameField;
        
        private string descriptionField;
        
        private customerEventDataV3[] eventDataListField;
        
        private string eventTimeField;
        
        private long objectIdField;
        
        private string packageReferenceField;
        
        private string parcelReferenceField;
        
        private string waybillField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string businessCode {
            get {
                return this.businessCodeField;
            }
            set {
                this.businessCodeField = value;
                this.RaisePropertyChanged("businessCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string depot {
            get {
                return this.depotField;
            }
            set {
                this.depotField = value;
                this.RaisePropertyChanged("depot");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string depotName {
            get {
                return this.depotNameField;
            }
            set {
                this.depotNameField = value;
                this.RaisePropertyChanged("depotName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("eventDataList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public customerEventDataV3[] eventDataList {
            get {
                return this.eventDataListField;
            }
            set {
                this.eventDataListField = value;
                this.RaisePropertyChanged("eventDataList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string eventTime {
            get {
                return this.eventTimeField;
            }
            set {
                this.eventTimeField = value;
                this.RaisePropertyChanged("eventTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public long objectId {
            get {
                return this.objectIdField;
            }
            set {
                this.objectIdField = value;
                this.RaisePropertyChanged("objectId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string packageReference {
            get {
                return this.packageReferenceField;
            }
            set {
                this.packageReferenceField = value;
                this.RaisePropertyChanged("packageReference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string parcelReference {
            get {
                return this.parcelReferenceField;
            }
            set {
                this.parcelReferenceField = value;
                this.RaisePropertyChanged("parcelReference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string waybill {
            get {
                return this.waybillField;
            }
            set {
                this.waybillField = value;
                this.RaisePropertyChanged("waybill");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/")]
    public partial class customerEventDataV3 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string descriptionField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEventsForWaybillV1", WrapperNamespace="http://events.dpdinfoservices.dpd.com.pl/", IsWrapped=true)]
    public partial class getEventsForWaybillV1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string waybill;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LajtIt.Bll.DpdStatusWCF.eventsSelectTypeEnum eventsSelectType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string language;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LajtIt.Bll.DpdStatusWCF.authDataV1 authDataV1;
        
        public getEventsForWaybillV1Request() {
        }
        
        public getEventsForWaybillV1Request(string waybill, LajtIt.Bll.DpdStatusWCF.eventsSelectTypeEnum eventsSelectType, string language, LajtIt.Bll.DpdStatusWCF.authDataV1 authDataV1) {
            this.waybill = waybill;
            this.eventsSelectType = eventsSelectType;
            this.language = language;
            this.authDataV1 = authDataV1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEventsForWaybillV1Response", WrapperNamespace="http://events.dpdinfoservices.dpd.com.pl/", IsWrapped=true)]
    public partial class getEventsForWaybillV1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LajtIt.Bll.DpdStatusWCF.customerEventsResponseV3 @return;
        
        public getEventsForWaybillV1Response() {
        }
        
        public getEventsForWaybillV1Response(LajtIt.Bll.DpdStatusWCF.customerEventsResponseV3 @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/")]
    public partial class customerEventsResponseV2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string confirmIdField;
        
        private customerEventV2[] eventsListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string confirmId {
            get {
                return this.confirmIdField;
            }
            set {
                this.confirmIdField = value;
                this.RaisePropertyChanged("confirmId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("eventsList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public customerEventV2[] eventsList {
            get {
                return this.eventsListField;
            }
            set {
                this.eventsListField = value;
                this.RaisePropertyChanged("eventsList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/")]
    public partial class customerEventV2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string businessCodeField;
        
        private string countryField;
        
        private string depotField;
        
        private string descriptionField;
        
        private customerEventDataV2[] eventDataListField;
        
        private string eventTimeField;
        
        private long idField;
        
        private long objectIdField;
        
        private string operationTypeField;
        
        private string packageReferenceField;
        
        private string parcelReferenceField;
        
        private string waybillField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string businessCode {
            get {
                return this.businessCodeField;
            }
            set {
                this.businessCodeField = value;
                this.RaisePropertyChanged("businessCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string depot {
            get {
                return this.depotField;
            }
            set {
                this.depotField = value;
                this.RaisePropertyChanged("depot");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("eventDataList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public customerEventDataV2[] eventDataList {
            get {
                return this.eventDataListField;
            }
            set {
                this.eventDataListField = value;
                this.RaisePropertyChanged("eventDataList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string eventTime {
            get {
                return this.eventTimeField;
            }
            set {
                this.eventTimeField = value;
                this.RaisePropertyChanged("eventTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public long objectId {
            get {
                return this.objectIdField;
            }
            set {
                this.objectIdField = value;
                this.RaisePropertyChanged("objectId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string operationType {
            get {
                return this.operationTypeField;
            }
            set {
                this.operationTypeField = value;
                this.RaisePropertyChanged("operationType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string packageReference {
            get {
                return this.packageReferenceField;
            }
            set {
                this.packageReferenceField = value;
                this.RaisePropertyChanged("packageReference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string parcelReference {
            get {
                return this.parcelReferenceField;
            }
            set {
                this.parcelReferenceField = value;
                this.RaisePropertyChanged("parcelReference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string waybill {
            get {
                return this.waybillField;
            }
            set {
                this.waybillField = value;
                this.RaisePropertyChanged("waybill");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/")]
    public partial class customerEventDataV2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEventsForCustomerV3", WrapperNamespace="http://events.dpdinfoservices.dpd.com.pl/", IsWrapped=true)]
    public partial class getEventsForCustomerV3Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int limit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LajtIt.Bll.DpdStatusWCF.authDataV1 authDataV1;
        
        public getEventsForCustomerV3Request() {
        }
        
        public getEventsForCustomerV3Request(int limit, LajtIt.Bll.DpdStatusWCF.authDataV1 authDataV1) {
            this.limit = limit;
            this.authDataV1 = authDataV1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEventsForCustomerV3Response", WrapperNamespace="http://events.dpdinfoservices.dpd.com.pl/", IsWrapped=true)]
    public partial class getEventsForCustomerV3Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LajtIt.Bll.DpdStatusWCF.customerEventsResponseV2 @return;
        
        public getEventsForCustomerV3Response() {
        }
        
        public getEventsForCustomerV3Response(LajtIt.Bll.DpdStatusWCF.customerEventsResponseV2 @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEventsForCustomerV4", WrapperNamespace="http://events.dpdinfoservices.dpd.com.pl/", IsWrapped=true)]
    public partial class getEventsForCustomerV4Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int limit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string language;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LajtIt.Bll.DpdStatusWCF.authDataV1 authDataV1;
        
        public getEventsForCustomerV4Request() {
        }
        
        public getEventsForCustomerV4Request(int limit, string language, LajtIt.Bll.DpdStatusWCF.authDataV1 authDataV1) {
            this.limit = limit;
            this.language = language;
            this.authDataV1 = authDataV1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEventsForCustomerV4Response", WrapperNamespace="http://events.dpdinfoservices.dpd.com.pl/", IsWrapped=true)]
    public partial class getEventsForCustomerV4Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LajtIt.Bll.DpdStatusWCF.customerEventsResponseV2 @return;
        
        public getEventsForCustomerV4Response() {
        }
        
        public getEventsForCustomerV4Response(LajtIt.Bll.DpdStatusWCF.customerEventsResponseV2 @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DPDInfoServicesObjEventsChannel : LajtIt.Bll.DpdStatusWCF.DPDInfoServicesObjEvents, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DPDInfoServicesObjEventsClient : System.ServiceModel.ClientBase<LajtIt.Bll.DpdStatusWCF.DPDInfoServicesObjEvents>, LajtIt.Bll.DpdStatusWCF.DPDInfoServicesObjEvents {
        
        public DPDInfoServicesObjEventsClient() {
        }
        
        public DPDInfoServicesObjEventsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DPDInfoServicesObjEventsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DPDInfoServicesObjEventsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DPDInfoServicesObjEventsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LajtIt.Bll.DpdStatusWCF.markEventsAsProcessedV1Response LajtIt.Bll.DpdStatusWCF.DPDInfoServicesObjEvents.markEventsAsProcessedV1(LajtIt.Bll.DpdStatusWCF.markEventsAsProcessedV1Request request) {
            return base.Channel.markEventsAsProcessedV1(request);
        }
        
        public bool markEventsAsProcessedV1(string confirmId, LajtIt.Bll.DpdStatusWCF.authDataV1 authDataV1) {
            LajtIt.Bll.DpdStatusWCF.markEventsAsProcessedV1Request inValue = new LajtIt.Bll.DpdStatusWCF.markEventsAsProcessedV1Request();
            inValue.confirmId = confirmId;
            inValue.authDataV1 = authDataV1;
            LajtIt.Bll.DpdStatusWCF.markEventsAsProcessedV1Response retVal = ((LajtIt.Bll.DpdStatusWCF.DPDInfoServicesObjEvents)(this)).markEventsAsProcessedV1(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LajtIt.Bll.DpdStatusWCF.getEventsForCustomerV1Response LajtIt.Bll.DpdStatusWCF.DPDInfoServicesObjEvents.getEventsForCustomerV1(LajtIt.Bll.DpdStatusWCF.getEventsForCustomerV1Request request) {
            return base.Channel.getEventsForCustomerV1(request);
        }
        
        public LajtIt.Bll.DpdStatusWCF.customerEventsResponseV1 getEventsForCustomerV1(int limit, LajtIt.Bll.DpdStatusWCF.authDataV1 authDataV1) {
            LajtIt.Bll.DpdStatusWCF.getEventsForCustomerV1Request inValue = new LajtIt.Bll.DpdStatusWCF.getEventsForCustomerV1Request();
            inValue.limit = limit;
            inValue.authDataV1 = authDataV1;
            LajtIt.Bll.DpdStatusWCF.getEventsForCustomerV1Response retVal = ((LajtIt.Bll.DpdStatusWCF.DPDInfoServicesObjEvents)(this)).getEventsForCustomerV1(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LajtIt.Bll.DpdStatusWCF.getEventsForCustomerV2Response LajtIt.Bll.DpdStatusWCF.DPDInfoServicesObjEvents.getEventsForCustomerV2(LajtIt.Bll.DpdStatusWCF.getEventsForCustomerV2Request request) {
            return base.Channel.getEventsForCustomerV2(request);
        }
        
        public LajtIt.Bll.DpdStatusWCF.customerEventsResponseV1 getEventsForCustomerV2(int limit, string language, LajtIt.Bll.DpdStatusWCF.authDataV1 authDataV1) {
            LajtIt.Bll.DpdStatusWCF.getEventsForCustomerV2Request inValue = new LajtIt.Bll.DpdStatusWCF.getEventsForCustomerV2Request();
            inValue.limit = limit;
            inValue.language = language;
            inValue.authDataV1 = authDataV1;
            LajtIt.Bll.DpdStatusWCF.getEventsForCustomerV2Response retVal = ((LajtIt.Bll.DpdStatusWCF.DPDInfoServicesObjEvents)(this)).getEventsForCustomerV2(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LajtIt.Bll.DpdStatusWCF.getEventsForWaybillV1Response LajtIt.Bll.DpdStatusWCF.DPDInfoServicesObjEvents.getEventsForWaybillV1(LajtIt.Bll.DpdStatusWCF.getEventsForWaybillV1Request request) {
            return base.Channel.getEventsForWaybillV1(request);
        }
        
        public LajtIt.Bll.DpdStatusWCF.customerEventsResponseV3 getEventsForWaybillV1(string waybill, LajtIt.Bll.DpdStatusWCF.eventsSelectTypeEnum eventsSelectType, string language, LajtIt.Bll.DpdStatusWCF.authDataV1 authDataV1) {
            LajtIt.Bll.DpdStatusWCF.getEventsForWaybillV1Request inValue = new LajtIt.Bll.DpdStatusWCF.getEventsForWaybillV1Request();
            inValue.waybill = waybill;
            inValue.eventsSelectType = eventsSelectType;
            inValue.language = language;
            inValue.authDataV1 = authDataV1;
            LajtIt.Bll.DpdStatusWCF.getEventsForWaybillV1Response retVal = ((LajtIt.Bll.DpdStatusWCF.DPDInfoServicesObjEvents)(this)).getEventsForWaybillV1(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LajtIt.Bll.DpdStatusWCF.getEventsForCustomerV3Response LajtIt.Bll.DpdStatusWCF.DPDInfoServicesObjEvents.getEventsForCustomerV3(LajtIt.Bll.DpdStatusWCF.getEventsForCustomerV3Request request) {
            return base.Channel.getEventsForCustomerV3(request);
        }
        
        public LajtIt.Bll.DpdStatusWCF.customerEventsResponseV2 getEventsForCustomerV3(int limit, LajtIt.Bll.DpdStatusWCF.authDataV1 authDataV1) {
            LajtIt.Bll.DpdStatusWCF.getEventsForCustomerV3Request inValue = new LajtIt.Bll.DpdStatusWCF.getEventsForCustomerV3Request();
            inValue.limit = limit;
            inValue.authDataV1 = authDataV1;
            LajtIt.Bll.DpdStatusWCF.getEventsForCustomerV3Response retVal = ((LajtIt.Bll.DpdStatusWCF.DPDInfoServicesObjEvents)(this)).getEventsForCustomerV3(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LajtIt.Bll.DpdStatusWCF.getEventsForCustomerV4Response LajtIt.Bll.DpdStatusWCF.DPDInfoServicesObjEvents.getEventsForCustomerV4(LajtIt.Bll.DpdStatusWCF.getEventsForCustomerV4Request request) {
            return base.Channel.getEventsForCustomerV4(request);
        }
        
        public LajtIt.Bll.DpdStatusWCF.customerEventsResponseV2 getEventsForCustomerV4(int limit, string language, LajtIt.Bll.DpdStatusWCF.authDataV1 authDataV1) {
            LajtIt.Bll.DpdStatusWCF.getEventsForCustomerV4Request inValue = new LajtIt.Bll.DpdStatusWCF.getEventsForCustomerV4Request();
            inValue.limit = limit;
            inValue.language = language;
            inValue.authDataV1 = authDataV1;
            LajtIt.Bll.DpdStatusWCF.getEventsForCustomerV4Response retVal = ((LajtIt.Bll.DpdStatusWCF.DPDInfoServicesObjEvents)(this)).getEventsForCustomerV4(inValue);
            return retVal.@return;
        }
    }
}
