//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace LajtIt.AllegroWeb {
    
    
    public partial class LampaWiszacaKronosTrio2Page {
        
        /// <summary>
        /// KronosMKolory1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LajtIt.AllegroWeb.Controls.KronosLKolory KronosMKolory1;
        
        /// <summary>
        /// Kronos1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LajtIt.AllegroWeb.Controls.Kronos Kronos1;
    }
}
