//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Ten kod źródłowy został wygenerowany automatycznie przez Microsoft.VSDesigner, wersja 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ConsoleApp1.LajtitService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AutoCompleteSoap", Namespace="http://tempuri.org/")]
    public partial class AutoComplete : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SetOrderReceiptCommandResultOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOrderReceiptCommandsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInvoicesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAttributeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetShopProducersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCompaniesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProductsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetShopCategoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSuppliersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFamiliesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGroupsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAttributeGroupsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAttributesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AutoComplete() {
            this.Url = global::ConsoleApp1.Properties.Settings.Default.ConsoleApp1_LajtitService_AutoComplete;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SetOrderReceiptCommandResultCompletedEventHandler SetOrderReceiptCommandResultCompleted;
        
        /// <remarks/>
        public event GetOrderReceiptCommandsCompletedEventHandler GetOrderReceiptCommandsCompleted;
        
        /// <remarks/>
        public event GetInvoicesCompletedEventHandler GetInvoicesCompleted;
        
        /// <remarks/>
        public event GetAttributeCompletedEventHandler GetAttributeCompleted;
        
        /// <remarks/>
        public event GetShopProducersCompletedEventHandler GetShopProducersCompleted;
        
        /// <remarks/>
        public event GetCompaniesCompletedEventHandler GetCompaniesCompleted;
        
        /// <remarks/>
        public event GetProductsCompletedEventHandler GetProductsCompleted;
        
        /// <remarks/>
        public event GetShopCategoryCompletedEventHandler GetShopCategoryCompleted;
        
        /// <remarks/>
        public event GetSuppliersCompletedEventHandler GetSuppliersCompleted;
        
        /// <remarks/>
        public event GetFamiliesCompletedEventHandler GetFamiliesCompleted;
        
        /// <remarks/>
        public event GetGroupsCompletedEventHandler GetGroupsCompleted;
        
        /// <remarks/>
        public event GetAttributeGroupsCompletedEventHandler GetAttributeGroupsCompleted;
        
        /// <remarks/>
        public event GetAttributesCompletedEventHandler GetAttributesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetOrderReceiptCommandResult", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetOrderReceiptCommandResult(int id, int statusId, string errorMsg) {
            this.Invoke("SetOrderReceiptCommandResult", new object[] {
                        id,
                        statusId,
                        errorMsg});
        }
        
        /// <remarks/>
        public void SetOrderReceiptCommandResultAsync(int id, int statusId, string errorMsg) {
            this.SetOrderReceiptCommandResultAsync(id, statusId, errorMsg, null);
        }
        
        /// <remarks/>
        public void SetOrderReceiptCommandResultAsync(int id, int statusId, string errorMsg, object userState) {
            if ((this.SetOrderReceiptCommandResultOperationCompleted == null)) {
                this.SetOrderReceiptCommandResultOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetOrderReceiptCommandResultOperationCompleted);
            }
            this.InvokeAsync("SetOrderReceiptCommandResult", new object[] {
                        id,
                        statusId,
                        errorMsg}, this.SetOrderReceiptCommandResultOperationCompleted, userState);
        }
        
        private void OnSetOrderReceiptCommandResultOperationCompleted(object arg) {
            if ((this.SetOrderReceiptCommandResultCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetOrderReceiptCommandResultCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetOrderReceiptCommands", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReceiptCommand[] GetOrderReceiptCommands(int id, string ip, bool isError, string errorMsg) {
            object[] results = this.Invoke("GetOrderReceiptCommands", new object[] {
                        id,
                        ip,
                        isError,
                        errorMsg});
            return ((ReceiptCommand[])(results[0]));
        }
        
        /// <remarks/>
        public void GetOrderReceiptCommandsAsync(int id, string ip, bool isError, string errorMsg) {
            this.GetOrderReceiptCommandsAsync(id, ip, isError, errorMsg, null);
        }
        
        /// <remarks/>
        public void GetOrderReceiptCommandsAsync(int id, string ip, bool isError, string errorMsg, object userState) {
            if ((this.GetOrderReceiptCommandsOperationCompleted == null)) {
                this.GetOrderReceiptCommandsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrderReceiptCommandsOperationCompleted);
            }
            this.InvokeAsync("GetOrderReceiptCommands", new object[] {
                        id,
                        ip,
                        isError,
                        errorMsg}, this.GetOrderReceiptCommandsOperationCompleted, userState);
        }
        
        private void OnGetOrderReceiptCommandsOperationCompleted(object arg) {
            if ((this.GetOrderReceiptCommandsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrderReceiptCommandsCompleted(this, new GetOrderReceiptCommandsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInvoices", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetInvoices(string query) {
            object[] results = this.Invoke("GetInvoices", new object[] {
                        query});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetInvoicesAsync(string query) {
            this.GetInvoicesAsync(query, null);
        }
        
        /// <remarks/>
        public void GetInvoicesAsync(string query, object userState) {
            if ((this.GetInvoicesOperationCompleted == null)) {
                this.GetInvoicesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInvoicesOperationCompleted);
            }
            this.InvokeAsync("GetInvoices", new object[] {
                        query}, this.GetInvoicesOperationCompleted, userState);
        }
        
        private void OnGetInvoicesOperationCompleted(object arg) {
            if ((this.GetInvoicesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInvoicesCompleted(this, new GetInvoicesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAttribute", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetAttribute(string query) {
            object[] results = this.Invoke("GetAttribute", new object[] {
                        query});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAttributeAsync(string query) {
            this.GetAttributeAsync(query, null);
        }
        
        /// <remarks/>
        public void GetAttributeAsync(string query, object userState) {
            if ((this.GetAttributeOperationCompleted == null)) {
                this.GetAttributeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAttributeOperationCompleted);
            }
            this.InvokeAsync("GetAttribute", new object[] {
                        query}, this.GetAttributeOperationCompleted, userState);
        }
        
        private void OnGetAttributeOperationCompleted(object arg) {
            if ((this.GetAttributeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAttributeCompleted(this, new GetAttributeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetShopProducers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetShopProducers(string query) {
            object[] results = this.Invoke("GetShopProducers", new object[] {
                        query});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetShopProducersAsync(string query) {
            this.GetShopProducersAsync(query, null);
        }
        
        /// <remarks/>
        public void GetShopProducersAsync(string query, object userState) {
            if ((this.GetShopProducersOperationCompleted == null)) {
                this.GetShopProducersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetShopProducersOperationCompleted);
            }
            this.InvokeAsync("GetShopProducers", new object[] {
                        query}, this.GetShopProducersOperationCompleted, userState);
        }
        
        private void OnGetShopProducersOperationCompleted(object arg) {
            if ((this.GetShopProducersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetShopProducersCompleted(this, new GetShopProducersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCompanies", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetCompanies(string query) {
            object[] results = this.Invoke("GetCompanies", new object[] {
                        query});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCompaniesAsync(string query) {
            this.GetCompaniesAsync(query, null);
        }
        
        /// <remarks/>
        public void GetCompaniesAsync(string query, object userState) {
            if ((this.GetCompaniesOperationCompleted == null)) {
                this.GetCompaniesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCompaniesOperationCompleted);
            }
            this.InvokeAsync("GetCompanies", new object[] {
                        query}, this.GetCompaniesOperationCompleted, userState);
        }
        
        private void OnGetCompaniesOperationCompleted(object arg) {
            if ((this.GetCompaniesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCompaniesCompleted(this, new GetCompaniesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetProducts", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetProducts(string query) {
            object[] results = this.Invoke("GetProducts", new object[] {
                        query});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetProductsAsync(string query) {
            this.GetProductsAsync(query, null);
        }
        
        /// <remarks/>
        public void GetProductsAsync(string query, object userState) {
            if ((this.GetProductsOperationCompleted == null)) {
                this.GetProductsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductsOperationCompleted);
            }
            this.InvokeAsync("GetProducts", new object[] {
                        query}, this.GetProductsOperationCompleted, userState);
        }
        
        private void OnGetProductsOperationCompleted(object arg) {
            if ((this.GetProductsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProductsCompleted(this, new GetProductsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetShopCategory", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ListItem[] GetShopCategory(int shopTypeId, string shopCategoryId) {
            object[] results = this.Invoke("GetShopCategory", new object[] {
                        shopTypeId,
                        shopCategoryId});
            return ((ListItem[])(results[0]));
        }
        
        /// <remarks/>
        public void GetShopCategoryAsync(int shopTypeId, string shopCategoryId) {
            this.GetShopCategoryAsync(shopTypeId, shopCategoryId, null);
        }
        
        /// <remarks/>
        public void GetShopCategoryAsync(int shopTypeId, string shopCategoryId, object userState) {
            if ((this.GetShopCategoryOperationCompleted == null)) {
                this.GetShopCategoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetShopCategoryOperationCompleted);
            }
            this.InvokeAsync("GetShopCategory", new object[] {
                        shopTypeId,
                        shopCategoryId}, this.GetShopCategoryOperationCompleted, userState);
        }
        
        private void OnGetShopCategoryOperationCompleted(object arg) {
            if ((this.GetShopCategoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetShopCategoryCompleted(this, new GetShopCategoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSuppliers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CascadingDropDownNameValue[] GetSuppliers(string knownCategoryValues, string category) {
            object[] results = this.Invoke("GetSuppliers", new object[] {
                        knownCategoryValues,
                        category});
            return ((CascadingDropDownNameValue[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSuppliersAsync(string knownCategoryValues, string category) {
            this.GetSuppliersAsync(knownCategoryValues, category, null);
        }
        
        /// <remarks/>
        public void GetSuppliersAsync(string knownCategoryValues, string category, object userState) {
            if ((this.GetSuppliersOperationCompleted == null)) {
                this.GetSuppliersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSuppliersOperationCompleted);
            }
            this.InvokeAsync("GetSuppliers", new object[] {
                        knownCategoryValues,
                        category}, this.GetSuppliersOperationCompleted, userState);
        }
        
        private void OnGetSuppliersOperationCompleted(object arg) {
            if ((this.GetSuppliersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSuppliersCompleted(this, new GetSuppliersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFamilies", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CascadingDropDownNameValue[] GetFamilies(string knownCategoryValues, string category) {
            object[] results = this.Invoke("GetFamilies", new object[] {
                        knownCategoryValues,
                        category});
            return ((CascadingDropDownNameValue[])(results[0]));
        }
        
        /// <remarks/>
        public void GetFamiliesAsync(string knownCategoryValues, string category) {
            this.GetFamiliesAsync(knownCategoryValues, category, null);
        }
        
        /// <remarks/>
        public void GetFamiliesAsync(string knownCategoryValues, string category, object userState) {
            if ((this.GetFamiliesOperationCompleted == null)) {
                this.GetFamiliesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFamiliesOperationCompleted);
            }
            this.InvokeAsync("GetFamilies", new object[] {
                        knownCategoryValues,
                        category}, this.GetFamiliesOperationCompleted, userState);
        }
        
        private void OnGetFamiliesOperationCompleted(object arg) {
            if ((this.GetFamiliesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFamiliesCompleted(this, new GetFamiliesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetGroups", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CascadingDropDownNameValue[] GetGroups(string knownCategoryValues, string category) {
            object[] results = this.Invoke("GetGroups", new object[] {
                        knownCategoryValues,
                        category});
            return ((CascadingDropDownNameValue[])(results[0]));
        }
        
        /// <remarks/>
        public void GetGroupsAsync(string knownCategoryValues, string category) {
            this.GetGroupsAsync(knownCategoryValues, category, null);
        }
        
        /// <remarks/>
        public void GetGroupsAsync(string knownCategoryValues, string category, object userState) {
            if ((this.GetGroupsOperationCompleted == null)) {
                this.GetGroupsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGroupsOperationCompleted);
            }
            this.InvokeAsync("GetGroups", new object[] {
                        knownCategoryValues,
                        category}, this.GetGroupsOperationCompleted, userState);
        }
        
        private void OnGetGroupsOperationCompleted(object arg) {
            if ((this.GetGroupsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGroupsCompleted(this, new GetGroupsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAttributeGroups", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CascadingDropDownNameValue[] GetAttributeGroups(string knownCategoryValues, string category) {
            object[] results = this.Invoke("GetAttributeGroups", new object[] {
                        knownCategoryValues,
                        category});
            return ((CascadingDropDownNameValue[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAttributeGroupsAsync(string knownCategoryValues, string category) {
            this.GetAttributeGroupsAsync(knownCategoryValues, category, null);
        }
        
        /// <remarks/>
        public void GetAttributeGroupsAsync(string knownCategoryValues, string category, object userState) {
            if ((this.GetAttributeGroupsOperationCompleted == null)) {
                this.GetAttributeGroupsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAttributeGroupsOperationCompleted);
            }
            this.InvokeAsync("GetAttributeGroups", new object[] {
                        knownCategoryValues,
                        category}, this.GetAttributeGroupsOperationCompleted, userState);
        }
        
        private void OnGetAttributeGroupsOperationCompleted(object arg) {
            if ((this.GetAttributeGroupsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAttributeGroupsCompleted(this, new GetAttributeGroupsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAttributes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CascadingDropDownNameValue[] GetAttributes(string knownCategoryValues, string category) {
            object[] results = this.Invoke("GetAttributes", new object[] {
                        knownCategoryValues,
                        category});
            return ((CascadingDropDownNameValue[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAttributesAsync(string knownCategoryValues, string category) {
            this.GetAttributesAsync(knownCategoryValues, category, null);
        }
        
        /// <remarks/>
        public void GetAttributesAsync(string knownCategoryValues, string category, object userState) {
            if ((this.GetAttributesOperationCompleted == null)) {
                this.GetAttributesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAttributesOperationCompleted);
            }
            this.InvokeAsync("GetAttributes", new object[] {
                        knownCategoryValues,
                        category}, this.GetAttributesOperationCompleted, userState);
        }
        
        private void OnGetAttributesOperationCompleted(object arg) {
            if ((this.GetAttributesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAttributesCompleted(this, new GetAttributesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceiptCommand {
        
        private int idField;
        
        private int receiptIdField;
        
        private string xmlField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int ReceiptId {
            get {
                return this.receiptIdField;
            }
            set {
                this.receiptIdField = value;
            }
        }
        
        /// <remarks/>
        public string Xml {
            get {
                return this.xmlField;
            }
            set {
                this.xmlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CascadingDropDownNameValue {
        
        private string nameField;
        
        private string valueField;
        
        private bool isDefaultValueField;
        
        private string optionTitleField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public bool isDefaultValue {
            get {
                return this.isDefaultValueField;
            }
            set {
                this.isDefaultValueField = value;
            }
        }
        
        /// <remarks/>
        public string optionTitle {
            get {
                return this.optionTitleField;
            }
            set {
                this.optionTitleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ListItem {
        
        private string textField;
        
        private string valueField;
        
        private bool enabledField;
        
        private bool selectedField;
        
        public ListItem() {
            this.textField = "";
            this.valueField = "";
            this.enabledField = true;
            this.selectedField = false;
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Selected {
            get {
                return this.selectedField;
            }
            set {
                this.selectedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void SetOrderReceiptCommandResultCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetOrderReceiptCommandsCompletedEventHandler(object sender, GetOrderReceiptCommandsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrderReceiptCommandsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrderReceiptCommandsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReceiptCommand[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReceiptCommand[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetInvoicesCompletedEventHandler(object sender, GetInvoicesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInvoicesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInvoicesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetAttributeCompletedEventHandler(object sender, GetAttributeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAttributeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAttributeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetShopProducersCompletedEventHandler(object sender, GetShopProducersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetShopProducersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetShopProducersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetCompaniesCompletedEventHandler(object sender, GetCompaniesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCompaniesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCompaniesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetProductsCompletedEventHandler(object sender, GetProductsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProductsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProductsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetShopCategoryCompletedEventHandler(object sender, GetShopCategoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetShopCategoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetShopCategoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListItem[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListItem[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetSuppliersCompletedEventHandler(object sender, GetSuppliersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSuppliersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSuppliersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CascadingDropDownNameValue[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CascadingDropDownNameValue[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetFamiliesCompletedEventHandler(object sender, GetFamiliesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFamiliesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFamiliesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CascadingDropDownNameValue[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CascadingDropDownNameValue[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetGroupsCompletedEventHandler(object sender, GetGroupsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGroupsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGroupsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CascadingDropDownNameValue[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CascadingDropDownNameValue[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetAttributeGroupsCompletedEventHandler(object sender, GetAttributeGroupsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAttributeGroupsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAttributeGroupsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CascadingDropDownNameValue[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CascadingDropDownNameValue[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetAttributesCompletedEventHandler(object sender, GetAttributesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAttributesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAttributesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CascadingDropDownNameValue[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CascadingDropDownNameValue[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591